### ISSUE TITLE
"host_overrride" broken and/or hard to get right

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#42]
The documentation of "host_override" in config.json is unclear.

Does it go in the wave block or outside it? 

Either way, I get fatal errors. Please provide an example of a complete config.json including host_override. This is my current version but moving the host_override line inside the wave block doesn't make any difference.

> {
>   "browser_host": "web-platform.test",
>   "wave": {
>     "aliases": [],
>     "results": "./results",
>     "timeouts": {
>         "automatic": 300000,
>         "manual": 300000
>     },
>     "enable_results_import": false,
>     "web_root": "/_wave",
>     "persisting_interval": 20,
>     "api_titles": [],
>     "host_override": "192.168.40.43"
>   }
> }

Here are the error messages.

dpctf    | This software comes with ABSOLUTELY NO WARRANTY.
dpctf    | Dnsmasq is free software, and you are welcome to redistribute it
dpctf    | under the terms of the GNU General Public License, version 2 or 3.
dpctf    | Starting test server ...
dpctf    | Traceback (most recent call last):
dpctf    |   File "./wpt", line 21, in <module>
dpctf    |     wpt.main()
dpctf    |   File "/home/ubuntu/DPCTF/tools/wpt/wpt.py", line 171, in main
dpctf    |     rv = script(*args, **kwargs)
dpctf    |   File "/home/ubuntu/DPCTF/tools/serve/wave.py", line 100, in run
dpctf    |     route_builder=get_route_builder_func(kwargs["report"]), **kwargs)
dpctf    |   File "/home/ubuntu/DPCTF/tools/serve/serve.py", line 953, in run
dpctf    |     **kwargs) as config:
dpctf    |   File "/home/ubuntu/DPCTF/tools/serve/serve.py", line 901, in build_config
dpctf    |     rv.update(override_obj)
dpctf    |   File "/home/ubuntu/DPCTF/tools/wptserve/wptserve/config.py", line 256, in update
dpctf    |     raise KeyError("unknown config override '%s'" % k)
dpctf    | KeyError: u"unknown config override 'host_override'"
dpctf    | ln: failed to create symbolic link './*': File exists
dpctf    | Checking EULA agreement ...
dpctf    | Checking permissions ...
dpctf    | Checking host_override IP '192.168.40.43' ...
dpctf    | Starting DNS server ...
dpctf    | Dnsmasq version 2.79  Copyright (c) 2000-2018 Simon Kelley
dpctf    | Compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth nettlehash DNSSEC loop-detect inotify
dpctf    | 
dpctf    | This software comes with ABSOLUTELY NO WARRANTY.
dpctf    | Dnsmasq is free software, and you are welcome to redistribute it
dpctf    | under the terms of the GNU General Public License, version 2 or 3.
dpctf    | Starting test server ...
dpctf    | Traceback (most recent call last):
dpctf    |   File "./wpt", line 21, in <module>
dpctf    |     wpt.main()
dpctf    |   File "/home/ubuntu/DPCTF/tools/wpt/wpt.py", line 171, in main
dpctf    |     rv = script(*args, **kwargs)
dpctf    |   File "/home/ubuntu/DPCTF/tools/serve/wave.py", line 100, in run
dpctf    |     route_builder=get_route_builder_func(kwargs["report"]), **kwargs)
dpctf    |   File "/home/ubuntu/DPCTF/tools/serve/serve.py", line 953, in run
dpctf    |     **kwargs) as config:
dpctf    |   File "/home/ubuntu/DPCTF/tools/serve/serve.py", line 901, in build_config
dpctf    |     rv.update(override_obj)
dpctf    |   File "/home/ubuntu/DPCTF/tools/wptserve/wptserve/config.py", line 256, in update
dpctf    |     raise KeyError("unknown config override '%s'" % k)
dpctf    | KeyError: u"unknown config override 'host_override'"

**Comment by gitwjr** [comment]
While we are implementing the warning in text, we can add they are using an IP test. If an https test is selected additional steps are required. Add a warning message if an https test is selected and the test runner was accessed using an IP address. Add in js in the browser.

**Comment by jpiesing** [comment]
This is addressed by QUICK_START.md.
