### ISSUE TITLE
default out of the box install should just work

### ISSUE THREAD

**Issue by jpiesing** [cta-wave/dpctf-deploy#6]
The default out of the box installation should just work to some extent and doesn't.

docker-compose.yml has 'image: dpctf:0.0.0' and not 'image: latest' which is what's used earlier in the instructions.

The URL in the QR code generated references localhost which doesn't work.

If I use host_override as documented with the IP address of the machine where docker is running then the instructions about running the tests don't work.

![image](https://user-images.githubusercontent.com/8490792/115004165-cf067a00-9ea6-11eb-86c2-bcff86c451e8.png)

Neither localhost:8000 nor (in this case) 192.168.40.53:8000 work.

**Comment by louaybassbouss** [comment]
@jpiesing image in `docker-compose.yml` is now changed to `dpctf:latest`.  The default networking mode is now `bridge`. On my mac it works as described in the documentation. Eurofins uses this option as well. Can you please try again maybe the issue was the networking mode (which was not the case for ubuntu). can you send your `config.json`? this config works on my side:

```json
{
  "browser_host": "web-platform.test",
  "wave": {
    "host_override": "192.168.2.116",
    "aliases": [],
    "results": "./results",
    "timeouts": {
        "automatic": 60000,
        "manual": 300000
    },
    "enable_results_import": false,
    "web_root": "/_wave",
    "persisting_interval": 20,
    "api_titles": []
  }
}
```

Please make sure to put `"host_override"` under `"wave"` and not in the main json.

**Comment by jpiesing** [comment]
@louaybassbouss This is what I have right now;

{
  "browser_host": "web-platform.test",
  "wave": {
    "aliases": [],
    "results": "./results",
    "timeouts": {
        "automatic": 60000,
        "manual": 300000
    },
    "enable_results_import": false,
    "web_root": "/_wave",
    "persisting_interval": 20,
    "api_titles": []
    "host_override": "192.168.40.53"
  }
}

Essentially I just added host override to what was in github.

Is there a logflle somewhere where any error messages would be recorded?

**Comment by jpiesing** [comment]
Bridge networking appears to have worked as expected - you can see the docker0 network interface which is what I would expect for this kind of networking.

jon@orion:~/TV_Standards/CTA/wave/dpctf-test-deployment/dpctf-deploy$ ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 172.17.0.1  netmask 255.255.0.0  broadcast 172.17.255.255
        inet6 fe80::42:8bff:fe2a:2e80  prefixlen 64  scopeid 0x20<link>
        ether 02:42:8b:2a:2e:80  txqueuelen 0  (Ethernet)
        RX packets 83111  bytes 4890105 (4.8 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 101354  bytes 816846677 (816.8 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp3s0f0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether f8:75:a4:92:8f:a6  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

enp4s0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether f8:75:a4:92:8f:a5  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 571545  bytes 44340854 (44.3 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 571545  bytes 44340854 (44.3 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp1s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.40.53  netmask 255.255.255.0  broadcast 192.168.40.255
        inet6 fe80::fbb:31e9:776:6ed0  prefixlen 64  scopeid 0x20<link>
        ether 0c:7a:15:a0:46:d7  txqueuelen 1000  (Ethernet)
        RX packets 32765881  bytes 30298838329 (30.2 GB)
        RX errors 0  dropped 6  overruns 0  frame 0
        TX packets 14101293  bytes 3342640964 (3.3 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by jpiesing** [comment]
The logs show a failure as follows;

INFO:web-platform-tests:Starting http2 server on web-platform.test:9000
INFO:web-platform-tests:Starting http server on web-platform.test:8000
INFO:web-platform-tests:Starting http server on web-platform.test:33083
INFO:web-platform-tests:Starting https server on web-platform.test:8443
DEBUG:web-platform-tests:Received signal 15. Shutting down.
INFO:web-platform-tests:Status of subprocess "h2 on port 9000": running
INFO:web-platform-tests:Status of subprocess "ws on port 46849": running
INFO:web-platform-tests:Status of subprocess "wss on port 53493": running
INFO:web-platform-tests:Status of subprocess "http on port 8000": running
INFO:web-platform-tests:Status of subprocess "http on port 33083": running
INFO:web-platform-tests:Status of subprocess "https on port 8443": running
Traceback (most recent call last):
  File "./wpt", line 21, in <module>
    wpt.main()
  File "/home/ubuntu/DPCTF/tools/wpt/wpt.py", line 171, in main
    rv = script(*args, **kwargs)
  File "/home/ubuntu/DPCTF/tools/serve/wave.py", line 100, in run
    route_builder=get_route_builder_func(kwargs["report"]), **kwargs)
  File "/home/ubuntu/DPCTF/tools/serve/serve.py", line 953, in run
    **kwargs) as config:
  File "/home/ubuntu/DPCTF/tools/serve/serve.py", line 900, in build_config
    override_obj = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 14 column 5 (char 296)
Traceback (most recent call last):
  File "./wpt", line 21, in <module>
    wpt.main()
  File "/home/ubuntu/DPCTF/tools/wpt/wpt.py", line 171, in main
    rv = script(*args, **kwargs)
  File "/home/ubuntu/DPCTF/tools/serve/wave.py", line 100, in run
    route_builder=get_route_builder_func(kwargs["report"]), **kwargs)
  File "/home/ubuntu/DPCTF/tools/serve/serve.py", line 953, in run
    **kwargs) as config:
  File "/home/ubuntu/DPCTF/tools/serve/serve.py", line 900, in build_config
    override_obj = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 14 column 5 (char 296)
Traceback (most recent call last):
  File "./wpt", line 21, in <module>
    wpt.main()
  File "/home/ubuntu/DPCTF/tools/wpt/wpt.py", line 171, in main
    rv = script(*args, **kwargs)
  File "/home/ubuntu/DPCTF/tools/serve/wave.py", line 100, in run
    route_builder=get_route_builder_func(kwargs["report"]), **kwargs)
  File "/home/ubuntu/DPCTF/tools/serve/serve.py", line 953, in run
    **kwargs) as config:
  File "/home/ubuntu/DPCTF/tools/serve/serve.py", line 900, in build_config
    override_obj = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 14 column 5 (char 296)
Traceback (most recent call last):
  File "./wpt", line 21, in <module>
    wpt.main()
  File "/home/ubuntu/DPCTF/tools/wpt/wpt.py", line 171, in main
    rv = script(*args, **kwargs)
  File "/home/ubuntu/DPCTF/tools/serve/wave.py", line 100, in run
    route_builder=get_route_builder_func(kwargs["report"]), **kwargs)
  File "/home/ubuntu/DPCTF/tools/serve/serve.py", line 953, in run
    **kwargs) as config:
  File "/home/ubuntu/DPCTF/tools/serve/serve.py", line 900, in build_config
    override_obj = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 14 column 5 (char 296)
Traceback (most recent call last):
  File "./wpt", line 21, in <module>
    wpt.main()
  File "/home/ubuntu/DPCTF/tools/wpt/wpt.py", line 171, in main
    rv = script(*args, **kwargs)
  File "/home/ubuntu/DPCTF/tools/serve/wave.py", line 100, in run
    route_builder=get_route_builder_func(kwargs["report"]), **kwargs)
  File "/home/ubuntu/DPCTF/tools/serve/serve.py", line 953, in run
    **kwargs) as config:
  File "/home/ubuntu/DPCTF/tools/serve/serve.py", line 900, in build_config
    override_obj = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 14 column 5 (char 296)
Traceback (most recent call last):
  File "./wpt", line 21, in <module>
    wpt.main()
  File "/home/ubuntu/DPCTF/tools/wpt/wpt.py", line 171, in main
    rv = script(*args, **kwargs)
  File "/home/ubuntu/DPCTF/tools/serve/wave.py", line 100, in run
    route_builder=get_route_builder_func(kwargs["report"]), **kwargs)
  File "/home/ubuntu/DPCTF/tools/serve/serve.py", line 953, in run
    **kwargs) as config:
  File "/home/ubuntu/DPCTF/tools/serve/serve.py", line 900, in build_config
    override_obj = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 14 column 5 (char 296)
Traceback (most recent call last):
  File "./wpt", line 21, in <module>
    wpt.main()
  File "/home/ubuntu/DPCTF/tools/wpt/wpt.py", line 171, in main
    rv = script(*args, **kwargs)
  File "/home/ubuntu/DPCTF/tools/serve/wave.py", line 100, in run
    route_builder=get_route_builder_func(kwargs["report"]), **kwargs)
  File "/home/ubuntu/DPCTF/tools/serve/serve.py", line 953, in run
    **kwargs) as config:
  File "/home/ubuntu/DPCTF/tools/serve/serve.py", line 900, in build_config
    override_obj = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 14 column 5 (char 296)
Traceback (most recent call last):
  File "./wpt", line 21, in <module>
    wpt.main()
  File "/home/ubuntu/DPCTF/tools/wpt/wpt.py", line 171, in main
    rv = script(*args, **kwargs)
  File "/home/ubuntu/DPCTF/tools/serve/wave.py", line 100, in run
    route_builder=get_route_builder_func(kwargs["report"]), **kwargs)
  File "/home/ubuntu/DPCTF/tools/serve/serve.py", line 953, in run
    **kwargs) as config:
  File "/home/ubuntu/DPCTF/tools/serve/serve.py", line 900, in build_config
    override_obj = json.load(f)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 14 column 5 (char 296)

**Comment by jpiesing** [comment]
Problem fixed - missing a "," in config.json.
